In [47]:
import pandas as pd

In [48]:
data = pd.read_excel(r"C:\Users\thepr\Desktop\yeast\Book1.xlsx")

In [49]:
data

CYT   NUC   MIT   ME3   ME2  ME1  EXC   VAC   POX  ERL
0     ADT1_YEAST  0.58  0.61  0.47  0.13  0.5  0.0  0.48  0.22  MIT
1     ADT2_YEAST  0.43  0.67  0.48  0.27  0.5  0.0  0.53  0.22  MIT
2     ADT3_YEAST  0.64  0.62  0.49  0.15  0.5  0.0  0.53  0.22  MIT
3     AAR2_YEAST  0.58  0.44  0.57  0.13  0.5  0.0  0.54  0.22  NUC
4     AATM_YEAST  0.42  0.44  0.48  0.54  0.5  0.0  0.48  0.22  MIT
...          ...   ...   ...   ...   ...  ...  ...   ...   ...  ...
1479  YUR1_YEAST  0.81  0.62  0.43  0.17  0.5  0.0  0.53  0.22  ME2
1480  ZIP1_YEAST  0.47  0.43  0.61  0.40  0.5  0.0  0.48  0.47  NUC
1481  ZNRP_YEAST  0.67  0.57  0.36  0.19  0.5  0.0  0.56  0.22  ME2
1482  ZUO1_YEAST  0.43  0.40   0.6  0.16  0.5  0.0  0.53  0.39  NUC
1483  G6PD_YEAST  0.65  0.54  0.54  0.13  0.5  0.0  0.53  0.22  CYT

[1484 rows x 10 columns]

In [50]:
data.drop('CYT',axis=1, inplace=True)

In [51]:
data

NUC   MIT   ME3   ME2  ME1  EXC   VAC   POX  ERL
0     0.58  0.61  0.47  0.13  0.5  0.0  0.48  0.22  MIT
1     0.43  0.67  0.48  0.27  0.5  0.0  0.53  0.22  MIT
2     0.64  0.62  0.49  0.15  0.5  0.0  0.53  0.22  MIT
3     0.58  0.44  0.57  0.13  0.5  0.0  0.54  0.22  NUC
4     0.42  0.44  0.48  0.54  0.5  0.0  0.48  0.22  MIT
...    ...   ...   ...   ...  ...  ...   ...   ...  ...
1479  0.81  0.62  0.43  0.17  0.5  0.0  0.53  0.22  ME2
1480  0.47  0.43  0.61  0.40  0.5  0.0  0.48  0.47  NUC
1481  0.67  0.57  0.36  0.19  0.5  0.0  0.56  0.22  ME2
1482  0.43  0.40   0.6  0.16  0.5  0.0  0.53  0.39  NUC
1483  0.65  0.54  0.54  0.13  0.5  0.0  0.53  0.22  CYT

[1484 rows x 9 columns]

In [52]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

data['ERL'] = encoded_categories = label_encoder.fit_transform(data['ERL'])

In [53]:
data['ERL'].unique()

array([6, 7, 0, 3, 2, 4, 5, 9, 8, 1])

In [54]:
data

NUC   MIT   ME3   ME2  ME1  EXC   VAC   POX  ERL
0     0.58  0.61  0.47  0.13  0.5  0.0  0.48  0.22    6
1     0.43  0.67  0.48  0.27  0.5  0.0  0.53  0.22    6
2     0.64  0.62  0.49  0.15  0.5  0.0  0.53  0.22    6
3     0.58  0.44  0.57  0.13  0.5  0.0  0.54  0.22    7
4     0.42  0.44  0.48  0.54  0.5  0.0  0.48  0.22    6
...    ...   ...   ...   ...  ...  ...   ...   ...  ...
1479  0.81  0.62  0.43  0.17  0.5  0.0  0.53  0.22    4
1480  0.47  0.43  0.61  0.40  0.5  0.0  0.48  0.47    7
1481  0.67  0.57  0.36  0.19  0.5  0.0  0.56  0.22    4
1482  0.43  0.40   0.6  0.16  0.5  0.0  0.53  0.39    7
1483  0.65  0.54  0.54  0.13  0.5  0.0  0.53  0.22    0

[1484 rows x 9 columns]

In [55]:
X = data.iloc[:,:-1]
y = data.iloc[:,-1]

In [56]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1484 entries, 0 to 1483
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   NUC     1484 non-null   float64
 1   MIT     1484 non-null   float64
 2   ME3     1484 non-null   object 
 3   ME2     1484 non-null   float64
 4   ME1     1484 non-null   float64
 5   EXC     1484 non-null   float64
 6   VAC     1484 non-null   float64
 7   POX     1484 non-null   float64
dtypes: float64(7), object(1)
memory usage: 92.9+ KB


In [57]:
data['ME3'].unique()

array([0.47, 0.48, 0.49, 0.57, 0.56, 0.59, 0.66, 0.6, 0.54, 0.52, 0.45,
       0.5, 0.55, 0.42, '0.53+D2', 0.36, 0.43, 0.61, 0.51, 0.53, 0.39,
       0.41, 0.58, 0.34, 0.44, 0.46, 0.63, 0.4, 0.21, 0.35, 0.62, 0.64,
       0.37, 0.29, 0.71, 0.33, 0.38, 0.3, 0.69, 0.31, 0.75, 0.72, 0.32,
       0.28, 0.65, 0.67, 0.68, 0.26, 0.27, 0.79, 1, 0.24, 0.22, 0.23],
      dtype=object)

In [58]:
def clean_and_convert(value):
    numeric_part = re.search(r'[-+]?\d*\.\d+|\d+', str(value))
    if numeric_part:
        return float(numeric_part.group())
    else:
        return None

In [59]:
import re
X = X.apply(lambda x:x.apply(clean_and_convert))

In [60]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [61]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1484 entries, 0 to 1483
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   NUC     1484 non-null   float64
 1   MIT     1484 non-null   float64
 2   ME3     1484 non-null   float64
 3   ME2     1484 non-null   float64
 4   ME1     1484 non-null   float64
 5   EXC     1484 non-null   float64
 6   VAC     1484 non-null   float64
 7   POX     1484 non-null   float64
dtypes: float64(8)
memory usage: 92.9 KB


In [62]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

## Random Forest

In [63]:
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier.fit(X_train, y_train)
rf_predictions = rf_classifier.predict(X_test)
rf_accuracy = accuracy_score(y_test, rf_predictions)
print("Random Forest Accuracy:", rf_accuracy)

Random Forest Accuracy: 0.6262626262626263


In [66]:
confusion_matrix(y_test, rf_predictions)

array([[59,  1,  0,  0,  3,  4, 29,  0,  0],
       [ 1,  4,  0,  0,  0,  3,  0,  0,  0],
       [ 0,  3,  5,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  1,  3,  0,  1,  1,  0,  0],
       [ 0,  0,  0,  1, 32,  0,  1,  0,  0],
       [10,  0,  0,  2,  3, 30,  7,  0,  0],
       [23,  0,  0,  0,  5,  6, 51,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  2,  0],
       [ 2,  1,  0,  0,  0,  1,  2,  0,  0]], dtype=int64)

## XGBoost

In [70]:
from xgboost import XGBClassifier

In [71]:
xgb_classifier = XGBClassifier(learning_rate=0.1, n_estimators=100, max_depth=3, random_state=42)
xgb_classifier.fit(X_train, y_train)
xgb_predictions = xgb_classifier.predict(X_test)
xgb_accuracy = accuracy_score(y_test, xgb_predictions)
print("XGBoost Accuracy:", xgb_accuracy)

XGBoost Accuracy: 0.622895622895623


In [72]:
confusion_matrix(y_test, xgb_predictions)

array([[62,  0,  0,  0,  2,  5, 27,  0,  0],
       [ 2,  4,  0,  0,  0,  2,  0,  0,  0],
       [ 0,  2,  6,  0,  0,  0,  0,  0,  0],
       [ 1,  0,  1,  3,  0,  1,  0,  0,  0],
       [ 0,  0,  0,  1, 30,  1,  2,  0,  0],
       [14,  0,  0,  2,  3, 28,  5,  0,  0],
       [23,  0,  0,  2,  5,  5, 50,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  2,  0],
       [ 1,  1,  1,  0,  0,  1,  2,  0,  0]], dtype=int64)

## SVM

In [74]:
from sklearn.svm import SVC

In [75]:
svm_classifier = SVC(kernel='linear', C=1, random_state=42)
svm_classifier.fit(X_train, y_train)
svm_predictions = svm_classifier.predict(X_test)
svm_accuracy = accuracy_score(y_test, svm_predictions)
print("SVM Accuracy:", svm_accuracy)

SVM Accuracy: 0.5757575757575758


In [76]:
confusion_matrix(y_test, svm_predictions)

array([[75,  0,  1,  0,  1,  2, 17,  0,  0],
       [ 2,  0,  2,  0,  0,  4,  0,  0,  0],
       [ 1,  0,  6,  0,  0,  1,  0,  0,  0],
       [ 2,  0,  1,  1,  0,  1,  1,  0,  0],
       [ 2,  0,  0,  0, 26,  1,  5,  0,  0],
       [20,  0,  0,  0,  2, 28,  2,  0,  0],
       [44,  0,  1,  0,  1,  6, 33,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  2,  0],
       [ 4,  0,  0,  0,  0,  2,  0,  0,  0]], dtype=int64)

## ANN

In [77]:
"# Decision Tree Regression
from sklearn.tree import DecisionTreeRegressor

dt_model = DecisionTreeRegressor()
dt_model.fit(X_train_scaled, y_train)
dt_pred = dt_model.predict(X_test_scaled)

dt_r2, dt_mse, dt_rmse = evaluate_model(y_test, dt_pred)
print(""Decision Tree Regression:"")
print(f""R2 Score: {dt_r2}"")
print(f""MSE: {dt_mse}"")
print(f""RMSE: {dt_rmse}"")"


In [86]:
model = Sequential()
model.add(Dense(8, input_dim=8, activation='relu'))
model.add(Dense(10, activation='softmax'))
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [90]:
import numpy as np

In [92]:
model.fit(X_train, y_train, epochs=50, batch_size=32, verbose=1)
keras_predictions = np.argmax(model.predict(X_test), axis=-1)
keras_accuracy = accuracy_score(y_test, keras_predictions)
print("Keras Accuracy:", keras_accuracy)

Epoch 1/50
38/38 [==============================] - 0s 1ms/step - loss: 1.1536 - accuracy: 0.5611
Epoch 2/50
38/38 [==============================] - 0s 1ms/step - loss: 1.1532 - accuracy: 0.5628
Epoch 3/50
38/38 [==============================] - 0s 1ms/step - loss: 1.1512 - accuracy: 0.5695
Epoch 4/50
38/38 [==============================] - 0s 1ms/step - loss: 1.1511 - accuracy: 0.5628
Epoch 5/50
38/38 [==============================] - 0s 1ms/step - loss: 1.1493 - accuracy: 0.5720
Epoch 6/50
38/38 [==============================] - 0s 1ms/step - loss: 1.1499 - accuracy: 0.5788
Epoch 7/50
38/38 [==============================] - 0s 1ms/step - loss: 1.1487 - accuracy: 0.5687
Epoch 8/50
38/38 [==============================] - 0s 1ms/step - loss: 1.1502 - accuracy: 0.5737
Epoch 9/50
38/38 [==============================] - 0s 1ms/step - loss: 1.1460 - accuracy: 0.5661
Epoch 10/50
38/38 [==============================] - 0s 1ms/step - loss: 1.1452 - accuracy: 0.5712
Epoch 11/50
38/38 [